### ISSUE TITLE
error: failed to compile `procmon-oprs v0.11.2

### ISSUE THREAD

**Issue by caedmon-kitty** [lparcq/procmon-oprs#1]
$ cargo install -f procmon-oprs
<Lines showing Successful compilation of prerequisites excluded>
   Compiling procmon-oprs v0.11.2
error[E0277]: the trait bound `std::vec::Vec<_>: std::convert::From<[u32; 12]>` is not satisfied
   --> /home/michaelr/.cargo/registry/src/github.com-1ecc6299db9ec823/procmon-oprs-0.11.2/src/export/rrd.rs:111:31
    |
111 |                 color_bucket: Vec::from(COLORS),
    |                               ^^^^^^^^^ the trait `std::convert::From<[u32; 12]>` is not implemented for `std::vec::Vec<_>`
    |
    = help: the following implementations were found:
              <std::vec::Vec<T> as std::convert::From<&[T]>>
              <std::vec::Vec<T> as std::convert::From<&mut [T]>>
              <std::vec::Vec<T> as std::convert::From<std::borrow::Cow<'a, [T]>>>
              <std::vec::Vec<T> as std::convert::From<std::boxed::Box<[T]>>>
            and 5 others
    = note: required by `std::convert::From::from`

error: aborting due to previous error

**Comment by lparcq** [comment]
I can't reproduce the compilation error. But I'll use to_vec instead of from to avoid the issue.
